service: aihouse-serverless

plugins:
  - serverless-python-requirements
  - serverless-localstack

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, "dev"}
  region: ap-northeast-1
  deploymentBucket:
    name: aihouse-serverless
  environment:
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
    CLIENT_ORIGIN_URL: ${env:CLIENT_ORIGIN_URL}
    AWS_KEY: ${env:AWS_KEY}
    AWS_SECRET: ${env:AWS_SECRET}

package:
  patterns:
    - '!Makefile'
    - '!poetry.lock'
    - '!README.md'
    - '!tests/**'
    - '!docs/**'
    - '!node_modules/**'
    - '!.venv/**'
    - '!.serverless/**'
    - '!package.json'
    - '!package-lock.json'
    - '!.pytest_cache'
    - '!.hypothesis'

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: aihouse-serverless-deps
      description: Dependencies of aihouse-serverless
      compatibleRuntimes:
        - python3.8

  localstack:
    stages:
      - local

functions:
  api:
    handler: api.main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}
  reservationHandler:
    handler: handler.reservation_handler.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - schedule:
          method: scheduler
          rate: cron(30 19 * * ? *)
          timezone: Asia/Tokyo
          # Invoke function everyday at 19:00 JST
# DynamoDB already exists
# resources:
#   Resources:
#     UserTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         TableName: User
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
